/* AUTOGENERATED FILE - DO NOT EDIT CONTENTS */

export const projectId = "edpnawsnseyiaxattupd"
export const publicAnonKey = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImVkcG5hd3Nuc2V5aWF4YXR0dXBkIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzEzOTQyODIsImV4cCI6MjA4Njk3MDI4Mn0.VXoUph9OoJs2FAqBs6drAP-AwTiWO-uMxmMwN32nVFA"